# Generated by Django 3.2 on 2021-04-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='number_of_pages',
            new_name='book_pages',
        ),
    ]
